# ES设置环境变量（直接配置ES和Memgraph连接信息）
ENV ES_HOST=es-cn-v641fgtry001dnl1g.public.elasticsearch.aliyuncs.com
ENV ES_PORT=9200
ENV ES_INDEX=aw_prod1
ENV ES_USER=elastic
ENV ES_PASSWORD=1qaz2wsx#EDC
ENV ES_USE_SSL=false
#图数据库配置
ENV MG_HOST=10.158.35.50
ENV MG_PORT=7687
ENV BATCH_SIZE=1000
# 是否从data.json读取数据（true/false）
# 本地调试时要先运行下：$env:LOAD_FROM_DATA_JSON="true"
ENV LOAD_FROM_DATA_JSON=true
